# Generated by Django 4.2.7 on 2024-01-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabify', '0004_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
