# Generated by Django 4.2.7 on 2024-01-18 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0006_alter_variant_image_alter_variant_quantity_and_more'),
        ('grabify', '0005_cart_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_admin.variant'),
        ),
    ]
