# Generated by Django 4.2.7 on 2024-01-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabify', '0007_orderdetails_arriving_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='quantity',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
