# Generated by Django 4.2.7 on 2024-01-27 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0009_alter_variant_size'),
        ('grabify', '0010_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_admin.product'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_admin.variant'),
        ),
    ]
