# Generated by Django 4.2.7 on 2024-02-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabify', '0012_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
