# Generated by Django 4.2.7 on 2024-01-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0003_variant_delete_variantimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='quantity',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
