# Generated by Django 4.2.7 on 2024-01-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0004_alter_variant_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('XS', 'XS'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=10),
        ),
    ]
