# Generated by Django 4.2.7 on 2024-01-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0005_alter_variant_quantity_alter_variant_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='image',
            field=models.ImageField(null=True, upload_to='product_images/variants/'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='quantity',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('XS', 'XS'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='M', max_length=10),
        ),
    ]
